"""
全局配置。所有路径、超参数集中管理。
修改内参时只需改 MANUAL_INTRINSICS 字段。
"""
import os
from pathlib import Path

# ── 根目录 ──────────────────────────────────────────────────────────────
ROOT = Path(__file__).parent.parent  # D:/face3D

# ── 模型权重路径 ────────────────────────────────────────────────────────
MODELS_DIR          = ROOT / "models"
FLAME_MODEL_PATH    = MODELS_DIR / "FLAME" / "generic_model.pkl"
FLAME_LANDMARK_PATH = MODELS_DIR / "FLAME" / "landmark_embedding.npy"  # FLAME→68点映射
DECA_MODEL_PATH     = MODELS_DIR / "DECA" / "deca_model.tar"
MICA_MODEL_PATH     = MODELS_DIR / "MICA" / "mica.tar"
EMOCA_MODEL_PATH    = MODELS_DIR / "EMOCA" / "EMOCA_v2_detail_EmotionMW_IDW_0.1"
DEPTH_MODEL_DIR     = MODELS_DIR / "depth_anything"

# ── 外部仓库路径 ────────────────────────────────────────────────────────
EXTERNAL_DIR   = ROOT / "external"
DECA_REPO_DIR  = EXTERNAL_DIR / "DECA"
DUST3R_DIR     = EXTERNAL_DIR / "dust3r"
MICA_REPO_DIR  = EXTERNAL_DIR / "MICA"
EMOCA_REPO_DIR = EXTERNAL_DIR / "EMOCA"

# ── 输出目录 ────────────────────────────────────────────────────────────
OUTPUT_DIR          = ROOT / "output"
OUTPUT_MESH_DIR     = OUTPUT_DIR / "meshes"
OUTPUT_TEXTURE_DIR  = OUTPUT_DIR / "textures"
OUTPUT_DEBUG_DIR    = OUTPUT_DIR / "debug"
CAMERA_CALIBRATION_PATH = ROOT / "config" / "camera_calibration.json"
WORK_IMAGE_SIZE = 1024
USE_CAMERA_CALIBRATION = True
UNDISTORT_IMAGES = True
UNDISTORT_ALPHA = 0.0
ENABLE_UV_HOLE_FILL_FACES = True
ENABLE_VISIBLE_FACE_CROP = True
VISIBLE_FACE_CROP_DILATE_RINGS = 1
VISIBLE_FACE_CROP_Z_TOL = 0.006
VISIBLE_FACE_CROP_STRICT_BOUNDARY = True
VISIBLE_FACE_CROP_ERODE_PX_AT_1024 = 1
VISIBLE_FACE_CROP_LOWER_STRICT_START = 0.78
VISIBLE_FACE_CROP_MIN_COMPONENT_FACES = 1000
VISIBLE_FACE_CROP_SIDE_EAR_TRIM = False
VISIBLE_FACE_CROP_SIDE_EAR_X_ABS_MIN = 0.066
VISIBLE_FACE_CROP_SIDE_EAR_Y_MIN = -0.060
VISIBLE_FACE_CROP_SIDE_EAR_Y_MAX = 0.060
VISIBLE_FACE_CROP_SIDE_EAR_Z_MAX = 0.004

# Repair bad side-ear texture patches without deleting valid face geometry.
ENABLE_SIDE_EAR_TEXTURE_REPAIR = True
SIDE_EAR_TEXTURE_REPAIR_X_ABS_MIN = 0.062
SIDE_EAR_TEXTURE_REPAIR_Y_MIN = -0.060
SIDE_EAR_TEXTURE_REPAIR_Y_MAX = 0.060
SIDE_EAR_TEXTURE_REPAIR_Z_MAX = 0.006
SIDE_EAR_TEXTURE_REPAIR_LAB_DELTA = 14.0
SIDE_EAR_TEXTURE_REPAIR_GRAD_LAB = 18.0
SIDE_EAR_TEXTURE_REPAIR_DILATE_PX = 2
SIDE_EAR_TEXTURE_REPAIR_INPAINT_RADIUS = 5
SIDE_EAR_TEXTURE_REPAIR_SMOOTH_ALPHA = 0.16
FORCE_CLOSED_EYES = False
CLOSED_EYE_GEOMETRY_STRENGTH = 0.95
CLOSED_EYE_LOSS_WEIGHT = 0.0
TEST_DATA_DIR       = OUTPUT_DIR / "test_data"   # generate_test_data.py 输出

# ── 输入图像命名约定 ─────────────────────────────────────────────────────
# key: 视角名, value: 文件名（相对于图像目录）
DEFAULT_VIEW_NAMES = {
    "left":   "camera1_20260519_102448.jpg",
    "front":  "camera2_20260519_102448.jpg",
    "right":  "camera3_20260519_102448.jpg",
}
DEFAULT_IMAGE_DIR = ROOT / "captures_20260519_102448"

# ── 相机内参（手动覆盖接口） ──────────────────────────────────────────────
# 若为 None，则由 Dust3R 预测；若设置则跳过 Dust3R 直接使用
# 格式: {"fx": float, "fy": float, "cx": float, "cy": float}
# 或直接传 3×3 numpy array
MANUAL_INTRINSICS = None
# vivo X300 主摄 1x，FocalLength=6.25mm，FocalLengthIn35mmFilm=23mm，3072×4080
# 推导：crop=3.68，pixel_pitch=0.002302mm，fx_original=2715px，缩放512后fx=341

# ── 初始化后端 ────────────────────────────────────────────────────────
# "face_alignment" : 仅用 face_alignment 68点（原有方案）
# "deca"           : 仅用 DECA 估计初值（原有方案）
# "mica_deca"      : MICA 估计共享身份形状 + DECA 估计每视角表情/姿态（推荐）
# "mica_emoca"     : MICA 估计共享身份形状 + EMOCA 估计每视角表情/姿态
INIT_BACKEND = "mica_deca"

# ── MICA 配置 ─────────────────────────────────────────────────────────
# MICA 权重目录（需下载 https://github.com/Zielon/MICA）
MICA_DIR        = MICA_REPO_DIR
MICA_CHECKPOINT = MICA_MODEL_PATH

# ── EMOCA 配置 ────────────────────────────────────────────────────────
# EMOCA 仓库与权重（https://github.com/radekd91/emoca）
EMOCA_DIR        = EMOCA_REPO_DIR
EMOCA_CHECKPOINT = EMOCA_MODEL_PATH

# ── DECA 配置 ─────────────────────────────────────────────────────────
DECA_DIR = DECA_REPO_DIR

# ── 3DMM 超参数 ────────────────────────────────────────────────────────
N_SHAPE_PARAMS  = 300   # FLAME 形状参数维度（最大300）
N_EXP_PARAMS    = 100   # FLAME 表情参数维度（最大100）
LAMBDA_SHAPE    = 5e-4  # 形状正则化权重（降低=更贴合真实脸型）
LAMBDA_EXP      = 5e-4  # 表情正则化权重
LBFGS_MAX_ITER  = 100   # L-BFGS 最大迭代次数（提升拟合精度）
LBFGS_LR        = 0.05  # 小学习率防止 NaN

# ── 脸型轮廓拟合超参数 ──────────────────────────────────────────────────
LAMBDA_CONTOUR = 0.0
FRONT_CONTOUR_WEIGHT = 2.4
FRONT_JAW_WEIGHT = 3.2
SIDE_CONTOUR_WEIGHT = 1.2
SIDE_JAW_WEIGHT = 1.8
SIDE_BROW_WEIGHT = 0.25
SIDE_EXTRA_SOFT_WEIGHT = 0.6
ENABLE_SHAPE_ONLY_FINE_TUNE = True
SHAPE_ONLY_MAX_ITER = 110
SHAPE_ONLY_LR = 0.035
SHAPE_ONLY_CONTOUR_SCALE = 1.7
SHAPE_ONLY_STABLE_ANCHOR_WEIGHT = 1.6
SHAPE_ONLY_DELTA_WEIGHT = 0.04
SHAPE_ONLY_MAX_PARAM_DELTA = 0.5
SHAPE_ONLY_MIN_CONTOUR_IMPROVE_PX = 0.05
SHAPE_ONLY_MAX_STABLE_WORSEN_PX = 2.0
SHAPE_ONLY_MAX_TOTAL_WORSEN_PX = 1.0
ENABLE_SHAPE_ONLY_DENSE_CONTOUR = True
SHAPE_ONLY_DENSE_CONTOUR_WEIGHT = 1.4
SHAPE_ONLY_DENSE_ROW_STEP = 6
SHAPE_ONLY_DENSE_ROW_SIGMA = 7.0
SHAPE_ONLY_DENSE_SOFTMIN_TAU = 10.0
SHAPE_ONLY_DENSE_BOUNDARY_BAND_PX = 90.0
SHAPE_ONLY_DENSE_SEARCH_MARGIN_PX = 70.0
SHAPE_ONLY_MIN_DENSE_CONTOUR_IMPROVE_PX = 0.25
SHAPE_ONLY_MAX_CONTOUR_WORSEN_PX = 2.3

# Camera pose refinement after shape-only tuning. This adjusts per-view R/t only;
# it does not deform mesh vertices or change UV/texture logic.
ENABLE_POSE_REFINEMENT = True
POSE_REFINE_MAX_ITER = 100
POSE_REFINE_LR = 0.003
POSE_REFINE_LMK_WEIGHT = 1.0
POSE_REFINE_STABLE_WEIGHT = 8.0
POSE_REFINE_DENSE_CONTOUR_WEIGHT = 0.08
POSE_REFINE_ROT_REG = 0.12
POSE_REFINE_TRANS_REG = 0.08
POSE_REFINE_MIN_MEAN_IMPROVE_PX = 1.0
POSE_REFINE_MIN_DENSE_IMPROVE_PX = 3.0
POSE_REFINE_MAX_MEAN_WORSEN_PX = 1.0
POSE_REFINE_MAX_STABLE_WORSEN_PX = 0.35
POSE_REFINE_MAX_MAXERR_WORSEN_PX = 5.0
POSE_REFINE_MAX_ROT_DEG = 4.5
POSE_REFINE_MAX_TRANS_REL = 0.08
POSE_REFINE_GLOBAL_MAX_OVERALL_WORSEN_PX = 0.75
POSE_REFINE_GLOBAL_MAX_FRONT_WORSEN_PX = 0.5
POSE_REFINE_GLOBAL_MAX_SIDE_DENSE_WORSEN_PX = 2.0

# ── 稳定面部锚点：防止自由修脸把表面拉碎 ─────────────────────────────────
ENABLE_STABLE_FACE_ANCHORS = True
STABLE_ANCHOR_NOSE_RADIUS_PX = 38.0
STABLE_ANCHOR_EYE_RADIUS_PX = 30.0
STABLE_ANCHOR_INNER_MOUTH_RADIUS_PX = 26.0
STABLE_ANCHOR_MAX_MOVE_M = 0.0005
DEFORM_GUARD_MAX_OFFSET_JUMP_P95_M = 0.012
DEFORM_GUARD_MAX_OFFSET_JUMP_M = 0.028

# ── 多视角验收：正脸变好时，侧脸不能被拖坏 ───────────────────────────────
ENABLE_MULTIVIEW_DEFORM_VALIDATION = True
MULTIVIEW_MIN_FRONT_IMPROVE_PX = 0.25
MULTIVIEW_MIN_OVERALL_IMPROVE_PX = 0.25
MULTIVIEW_MAX_SIDE_WORSEN_PX = 0.35
MULTIVIEW_MAX_SIDE_MEAN_WORSEN_PX = 0.15
MULTIVIEW_REQUIRE_SIDE_VIEWS = True

# ── 自由修脸：FLAME 之后的局部网格形变 ─────────────────────────────────────
ENABLE_FREE_FACE_DEFORM = False
FREE_FACE_MAX_OFFSET_M = 0.028
FREE_FACE_BOUNDARY_BAND_PX = 95.0
FREE_FACE_SEARCH_MARGIN_PX = 80.0
FREE_FACE_STABLE_PROTECT_RADIUS_PX = 42.0
FREE_FACE_MIN_VIEW_COS = 0.03
FREE_FACE_ROW_STEP = 6
FREE_FACE_ROW_SIGMA = 8.0
FREE_FACE_SOFTMIN_TAU = 10.0
FREE_FACE_ENVELOPE_TOPK = 28
FREE_FACE_VIEW_WEIGHT_FRONT = 1.0
FREE_FACE_VIEW_WEIGHT_SIDE = 0.0
FREE_FACE_MAX_STEP_PX = 80.0
FREE_FACE_SMOOTH_ITER = 16
FREE_FACE_SMOOTH_ALPHA = 0.2
FREE_FACE_CONSTRAINT_KEEP = 0.86
FREE_FACE_ACCEPT_MIN_IMPROVE_PX = 0.25
FREE_FACE_MAX_SIDE_WORSEN_PX = 2.0
FREE_FACE_MAX_MOVED_RATIO = 0.08

# ── 个体残差形变：FLAME 之后、深度置换之前的脸型补偿 ───────────────────
ENABLE_PERSONAL_RESIDUAL_DEFORM = True
PERSONAL_RESIDUAL_USE_SEMANTIC_CONTOUR = True
PERSONAL_RESIDUAL_USE_PROFILE_SIDE_CONTOUR = True
PERSONAL_RESIDUAL_SEMANTIC_MASK_DILATE_PX = 6.0
PERSONAL_RESIDUAL_SEMANTIC_EDIT_MARGIN_PX = 28.0
PERSONAL_RESIDUAL_MAX_OFFSET_M = 0.018
PERSONAL_RESIDUAL_BOUNDARY_BAND_PX = 95.0
PERSONAL_RESIDUAL_SEARCH_MARGIN_PX = 80.0
PERSONAL_RESIDUAL_STABLE_PROTECT_RADIUS_PX = 44.0
PERSONAL_RESIDUAL_MIN_VIEW_COS = 0.03
PERSONAL_RESIDUAL_ROW_STEP = 6
PERSONAL_RESIDUAL_ROW_SIGMA = 8.0
PERSONAL_RESIDUAL_SOFTMIN_TAU = 10.0
PERSONAL_RESIDUAL_ENVELOPE_TOPK = 26
PERSONAL_RESIDUAL_VIEW_WEIGHT_FRONT = 0.35
PERSONAL_RESIDUAL_VIEW_WEIGHT_SIDE = 1.0
PERSONAL_RESIDUAL_MAX_STEP_PX = 56.0
PERSONAL_RESIDUAL_SMOOTH_ITER = 30
PERSONAL_RESIDUAL_SMOOTH_ALPHA = 0.30
PERSONAL_RESIDUAL_CONSTRAINT_KEEP = 0.55
PERSONAL_RESIDUAL_TARGET_SIDE_IMPROVE_PX = 4.0
PERSONAL_RESIDUAL_MIN_SIDE_MEAN_IMPROVE_PX = 2.0
PERSONAL_RESIDUAL_MAX_STABLE_WORSEN_PX = 0.75
PERSONAL_RESIDUAL_MAX_GLOBAL_WORSEN_PX = 1.0
PERSONAL_RESIDUAL_MAX_SIDE_WORSEN_PX = 1.0
PERSONAL_RESIDUAL_MAX_MOVED_RATIO = 0.12

# ── 自由身份变形：FLAME 之后的局部 landmark handle 形变 ───────────────────
ENABLE_FREE_IDENTITY_DEFORM = False
FREE_IDENTITY_MAX_OFFSET_M = 0.028
FREE_IDENTITY_MAX_STEP_PX = 45.0
FREE_IDENTITY_RADIUS_PX = 42.0
FREE_IDENTITY_CONTOUR_RADIUS_PX = 56.0
FREE_IDENTITY_MOUTH_RADIUS_PX = 36.0
FREE_IDENTITY_VIEW_WEIGHT_FRONT = 1.0
FREE_IDENTITY_VIEW_WEIGHT_SIDE = 0.22
FREE_IDENTITY_MIN_VIEW_COS = 0.02
FREE_IDENTITY_SMOOTH_ITER = 18
FREE_IDENTITY_SMOOTH_ALPHA = 0.22
FREE_IDENTITY_CONSTRAINT_KEEP = 0.78
FREE_IDENTITY_MIN_IMPROVE_PX = 0.15
FREE_IDENTITY_MAX_STABLE_WORSEN_PX = 1.4
FREE_IDENTITY_MAX_SIDE_WORSEN_PX = 2.5
FREE_IDENTITY_MAX_MOVED_RATIO = 0.18

# ── 深度估计超参数 ──────────────────────────────────────────────────────
DEPTH_MODEL_SIZE = "large"       # "small"/"base"/"large"
DISPLACEMENT_SCALE = 0.002         # 顶点置换最大幅度（米）

# ── 硬件 ────────────────────────────────────────────────────────────────
DEVICE = "cuda"   # "cuda" or "cpu"

# ── 光照图层配置（多光照预留接口） ──────────────────────────────────────
LIGHTING_TYPES = {
    "white": {
        "display_name": "白光",
        "image_dir": str(DEFAULT_IMAGE_DIR),
        "views": DEFAULT_VIEW_NAMES,
    },
    # 预留接口示例（后续扩展）:
    # "uv": {
    #     "display_name": "UV光",
    #     "image_dir": str(ROOT / "image_uv"),
    #     "views": {...},
    # },
}
DEFAULT_LIGHTING = "white"

# ── 工具函数 ────────────────────────────────────────────────────────────
def ensure_dirs():
    """确保所有输出目录存在"""
    for d in [OUTPUT_MESH_DIR, OUTPUT_TEXTURE_DIR, OUTPUT_DEBUG_DIR]:
        d.mkdir(parents=True, exist_ok=True)
